version: "3.4"
services:
  api:
    container_name: ily-api
    build: ./app
    ports:
      - 4000:4000
  db:
    container_name: ily-db
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - dbName:/data/db

volumes:
  dbName:
